"""Train LightGBM models that predict strong initial schedule knobs.

Models are trained from `training_dataset.csv` generated by
`extract_training_data.py` and saved to
`research/results/ml_schedule_predictor/models/`.
"""

from __future__ import annotations

import argparse
import logging
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import joblib
import pandas as pd
from lightgbm import LGBMClassifier, LGBMRegressor
from sklearn.metrics import accuracy_score, mean_absolute_error
from sklearn.model_selection import train_test_split

LOGGER = logging.getLogger("train_lightgbm_knob_models")

RESEARCH_DIR = Path(__file__).resolve().parents[3]
DEFAULT_DATASET_PATH = RESEARCH_DIR / "results" / "ml_schedule_predictor" / "training_dataset.csv"
DEFAULT_MODELS_DIR = RESEARCH_DIR / "results" / "ml_schedule_predictor" / "models"

FEATURE_COLUMNS = [
    "kernel_type",
    "M",
    "K",
    "N",
    "M_div_8",
    "N_div_8",
    "K_div_8",
    "M_div_16",
    "N_div_16",
    "arithmetic_intensity_proxy",
    "reduction_ratio",
    "output_size",
    "flops",
]

MODEL_DEFAULTS: Dict[str, object] = {
    "n_estimators": 200,
    "learning_rate": 0.05,
    "num_leaves": 31,
    "max_depth": 6,
    "subsample": 0.8,
    "colsample_bytree": 0.8,
    "random_state": 42,
    "n_jobs": -1,
}

DEFAULT_LABEL_VALUES: Dict[str, float] = {
    "vector_width": 16.0,
    "unroll_factor": 128.0,
    "cache_write_used": 1.0,
    "reduction_decompose_used": 1.0,
}


def _prepare_features(dataframe: pd.DataFrame) -> pd.DataFrame:
    features = dataframe[FEATURE_COLUMNS].copy()
    features["kernel_type"] = features["kernel_type"].fillna("unknown").astype(str)

    numeric_columns = [column for column in FEATURE_COLUMNS if column != "kernel_type"]
    for column in numeric_columns:
        features[column] = pd.to_numeric(features[column], errors="coerce").fillna(0.0)

    encoded = pd.get_dummies(features, columns=["kernel_type"], dummy_na=False)
    return encoded


def _drop_constant_features(features: pd.DataFrame) -> pd.DataFrame:
    keep_columns = [
        column
        for column in features.columns
        if features[column].nunique(dropna=False) > 1
    ]
    return features[keep_columns]


def _build_model_params(num_rows: int) -> Dict[str, object]:
    params = dict(MODEL_DEFAULTS)

    # Tiny tabular datasets are common here, so lower split constraints.
    if num_rows < 64:
        params["min_child_samples"] = 1
        params["min_data_in_bin"] = 1

    # Keep logs from exploding with per-tree split warnings.
    params["verbosity"] = -1
    return params


def _save_model_artifact(
    model: object,
    feature_columns: List[str],
    output_path: Path,
    model_kind: str,
) -> None:
    payload = {
        "model": model,
        "feature_columns": feature_columns,
        "model_kind": model_kind,
    }
    joblib.dump(payload, output_path)


def _save_constant_artifact(
    output_path: Path,
    feature_columns: List[str],
    model_kind: str,
    value: float,
) -> None:
    payload = {
        "model": None,
        "feature_columns": feature_columns,
        "model_kind": f"constant_{model_kind}",
        "constant_value": float(value),
    }
    joblib.dump(payload, output_path)


def _print_feature_importance(model: object, feature_columns: List[str]) -> None:
    importances = getattr(model, "feature_importances_", None)
    if importances is None:
        LOGGER.info("Feature importance is unavailable for %s", type(model).__name__)
        return

    ranking = sorted(
        zip(feature_columns, importances),
        key=lambda item: float(item[1]),
        reverse=True,
    )

    if not ranking or all(float(score) == 0.0 for _, score in ranking):
        LOGGER.warning("All feature importances are zero for %s", type(model).__name__)
        return

    LOGGER.info("Feature importance ranking (%s):", type(model).__name__)
    for name, score in ranking:
        LOGGER.info("  %-35s %.4f", name, float(score))


def _safe_train_test_split(
    features: pd.DataFrame,
    labels: pd.Series,
    stratify: bool,
) -> Optional[Tuple[pd.DataFrame, pd.DataFrame, pd.Series, pd.Series]]:
    if len(features) < 4:
        return None

    test_size = 0.2
    if len(features) * test_size < 1:
        return None

    split_kwargs = {"test_size": test_size, "random_state": 42}
    if stratify and labels.nunique(dropna=True) > 1 and labels.value_counts().min() >= 2:
        split_kwargs["stratify"] = labels

    return train_test_split(features, labels, **split_kwargs)


def _majority_class(labels: pd.Series, fallback: float) -> float:
    if labels.empty:
        return float(fallback)
    counts = labels.value_counts(dropna=True)
    if counts.empty:
        return float(fallback)
    return float(counts.index[0])


def _regression_baseline(labels: pd.Series, fallback: float) -> float:
    if labels.empty:
        return float(fallback)
    return float(labels.median())


def train_classifier(
    dataframe: pd.DataFrame,
    label_column: str,
    output_path: Path,
) -> None:
    full_feature_columns = list(_prepare_features(dataframe).columns)
    subset = dataframe.dropna(subset=[label_column]).copy()
    if subset.empty:
        fallback = DEFAULT_LABEL_VALUES.get(label_column, 0.0)
        LOGGER.warning(
            "No non-null labels for %s; saving constant fallback model value=%s",
            label_column,
            int(fallback),
        )
        _save_constant_artifact(
            output_path=output_path,
            feature_columns=full_feature_columns,
            model_kind="classifier",
            value=fallback,
        )
        return

    x_data = _prepare_features(subset)
    y_data = pd.to_numeric(subset[label_column], errors="coerce").dropna().astype(int)
    x_data = x_data.loc[y_data.index]
    x_data = _drop_constant_features(x_data)

    fallback = _majority_class(y_data, DEFAULT_LABEL_VALUES.get(label_column, 0.0))

    LOGGER.info(
        "%s classifier dataset: rows=%d, features=%d, classes=%d",
        label_column,
        len(y_data),
        x_data.shape[1],
        y_data.nunique(),
    )

    if y_data.nunique() < 2:
        LOGGER.warning(
            "Only one class for %s; saving constant fallback model value=%s",
            label_column,
            int(fallback),
        )
        _save_constant_artifact(
            output_path=output_path,
            feature_columns=list(x_data.columns) or full_feature_columns,
            model_kind="classifier",
            value=fallback,
        )
        return

    if x_data.shape[1] == 0:
        LOGGER.warning(
            "No non-constant features for %s; saving constant fallback model value=%s",
            label_column,
            int(fallback),
        )
        _save_constant_artifact(
            output_path=output_path,
            feature_columns=full_feature_columns,
            model_kind="classifier",
            value=fallback,
        )
        return

    split = _safe_train_test_split(x_data, y_data, stratify=True)
    model = LGBMClassifier(**_build_model_params(len(y_data)))

    if split is None:
        LOGGER.warning("Dataset too small for validation split for %s; training on full data", label_column)
        model.fit(x_data, y_data)
        metric_text = "validation accuracy: n/a (dataset too small)"
    else:
        x_train, x_val, y_train, y_val = split
        model.fit(x_train, y_train)
        predictions = model.predict(x_val)
        accuracy = accuracy_score(y_val, predictions)
        metric_text = f"validation accuracy: {accuracy:.4f}"

    _save_model_artifact(model, list(x_data.columns), output_path, model_kind="classifier")
    LOGGER.info("Saved %s model to %s (%s)", label_column, output_path, metric_text)
    _print_feature_importance(model, list(x_data.columns))


def train_regressor(
    dataframe: pd.DataFrame,
    label_column: str,
    output_path: Path,
) -> None:
    full_feature_columns = list(_prepare_features(dataframe).columns)
    subset = dataframe.dropna(subset=[label_column]).copy()
    if subset.empty:
        fallback = DEFAULT_LABEL_VALUES.get(label_column, 0.0)
        LOGGER.warning(
            "No non-null labels for %s; saving constant fallback model value=%.3f",
            label_column,
            fallback,
        )
        _save_constant_artifact(
            output_path=output_path,
            feature_columns=full_feature_columns,
            model_kind="regressor",
            value=fallback,
        )
        return

    x_data = _prepare_features(subset)
    y_data = pd.to_numeric(subset[label_column], errors="coerce").dropna().astype(float)
    x_data = x_data.loc[y_data.index]
    x_data = _drop_constant_features(x_data)

    fallback = _regression_baseline(y_data, DEFAULT_LABEL_VALUES.get(label_column, 0.0))

    LOGGER.info(
        "%s regressor dataset: rows=%d, features=%d, label_unique=%d",
        label_column,
        len(y_data),
        x_data.shape[1],
        y_data.nunique(),
    )

    if y_data.nunique() < 2:
        LOGGER.warning(
            "Only one label value for %s; saving constant fallback model value=%.3f",
            label_column,
            fallback,
        )
        _save_constant_artifact(
            output_path=output_path,
            feature_columns=list(x_data.columns) or full_feature_columns,
            model_kind="regressor",
            value=fallback,
        )
        return

    if x_data.shape[1] == 0:
        LOGGER.warning(
            "No non-constant features for %s; saving constant fallback model value=%.3f",
            label_column,
            fallback,
        )
        _save_constant_artifact(
            output_path=output_path,
            feature_columns=full_feature_columns,
            model_kind="regressor",
            value=fallback,
        )
        return

    split = _safe_train_test_split(x_data, y_data, stratify=False)
    model = LGBMRegressor(**_build_model_params(len(y_data)))

    if split is None:
        LOGGER.warning("Dataset too small for validation split for %s; training on full data", label_column)
        model.fit(x_data, y_data)
        metric_text = "validation MAE: n/a (dataset too small)"
    else:
        x_train, x_val, y_train, y_val = split
        model.fit(x_train, y_train)
        predictions = model.predict(x_val)
        mae = mean_absolute_error(y_val, predictions)
        metric_text = f"validation MAE: {mae:.4f}"

    _save_model_artifact(model, list(x_data.columns), output_path, model_kind="regressor")
    LOGGER.info("Saved %s model to %s (%s)", label_column, output_path, metric_text)
    _print_feature_importance(model, list(x_data.columns))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train LightGBM schedule knob models")
    parser.add_argument(
        "--dataset",
        type=Path,
        default=DEFAULT_DATASET_PATH,
        help=f"Path to training dataset CSV (default: {DEFAULT_DATASET_PATH})",
    )
    parser.add_argument(
        "--models-dir",
        type=Path,
        default=DEFAULT_MODELS_DIR,
        help=f"Directory to save model artifacts (default: {DEFAULT_MODELS_DIR})",
    )
    parser.add_argument("--verbose", action="store_true", help="Enable debug logs")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s | %(levelname)s | %(message)s",
    )

    dataset_path = args.dataset
    if not dataset_path.exists():
        LOGGER.error("Training dataset not found: %s", dataset_path)
        return 1

    dataframe = pd.read_csv(dataset_path)
    missing_columns = [column for column in FEATURE_COLUMNS if column not in dataframe.columns]
    if missing_columns:
        LOGGER.error("Dataset is missing required columns: %s", missing_columns)
        return 1

    args.models_dir.mkdir(parents=True, exist_ok=True)

    train_classifier(
        dataframe,
        label_column="vector_width",
        output_path=args.models_dir / "vector_width_model.pkl",
    )
    train_regressor(
        dataframe,
        label_column="unroll_factor",
        output_path=args.models_dir / "unroll_model.pkl",
    )
    train_classifier(
        dataframe,
        label_column="cache_write_used",
        output_path=args.models_dir / "cache_write_model.pkl",
    )
    train_classifier(
        dataframe,
        label_column="reduction_decompose_used",
        output_path=args.models_dir / "decompose_model.pkl",
    )

    LOGGER.info("Finished model training")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
